feat : chatGpt api를 이용한 챗봇 기능 추가
kimmandoo/Ping pull request #24
Opened 2024-05-21 08:36 UTC by orangeshop

openAI의 api를 사용하여 챗봇 기능 추가하였습니다.
해당 기능을 구현하면서 어려웠던 점은 nine patch 문제가 있었으며 해당 문제의 해결점은 해상도의 문제였습니다.
또한 추가하려고 했던 ai가 추천하는 기능은 제외되었습니다.

2024-05-21 08:44 UTC, kimmandoo commented on app/src/main/java/com/ping/app/ui/ui/feature/chat/ChatAdapter.kt
> +        val formatter = DateTimeFormatter.ofPattern("a hh:mm")
SimpleDateFormat

2024-05-21 13:53 UTC, orangeshop commented on app/src/main/java/com/ping/app/ui/presentation/chat/ChatViewModel.kt
> +    }
이부분이 위치 가져와서 gpt에 넣는 부분인데 이렇게 위치를 가져오는 것보다 더 나은 방법이 있을 것 같은데 같이 설명해줬으면 해

2024-05-21 15:16 UTC, kimmandoo requested changes

2024-05-21 15:16 UTC, kimmandoo commented on app/src/main/java/com/ping/app/ui/presentation/chat/ChatViewModel.kt
> +    }
init블록에다가 하는 방법말고 suspend fun으로 감싸서 코루틴 스코프 하나 날리는게 나을 것 같아
그리고 viewmodel에는 viewModelScope가 있어서 이거 먼저 써야되고, 위치 찾는건 IO에서 굳이 안해도 돼
그리고 currentLocation으로 좌표 받아오는거 보다는 Fragment에서 PingMapViewModel에 있는 userLocation 갖다쓰는게 더 좋은 방법인 것 같아.

2024-05-21 15:16 UTC, kimmandoo commented on app/src/main/java/com/ping/app/ui/ui/feature/chat/ChatFragment.kt
>          val test = CompletableDeferred<ChatGptResponse>()
이런 비즈니스 로직들 다 뷰모델로 옮겨야돼

2024-05-22 01:54 UTC, kimmandoo approved these changes

2024-05-22 01:54 UTC, merged